### ISSUE TITLE
Problem installing on debian Raspberry PI

### ISSUE THREAD

**Issue by PaulHaeberli** [fogleman/axi#14]
I love this library, and I want to make a plot server to run on Raspbery PI.

Running the latest debian....

When I did

    pip install -e .

I got a bunch of errors about libgeos. After searching for solutions
I found that doing this seemed to fix that problem.

    sudo apt-get install libgeos-dev

Then when I ran

    pip install -e .

I get this error, which is strange since axi is python 3 right?

    RuntimeError: cairocffi does not support Python 2.x anymore. Please
    use Python 3 or install an older version of cairocffi.

Trace:

pi@raspberrypi:~/axi$ pip install -e .
Obtaining file:///home/pi/axi
  Running setup.py (path:/home/pi/axi/setup.py) egg_info for package
from file:///home/pi/axi

Requirement already satisfied (use --upgrade to upgrade): pyserial in
/usr/lib/python2.7/dist-packages (from axi==0.1)
Downloading/unpacking shapely (from axi==0.1)
  Downloading Shapely-1.6.4.post2.tar.gz (225kB): 225kB downloaded
  Running setup.py (path:/tmp/pip-build-uVKpez/shapely/setup.py)
egg_info for package shapely

Downloading/unpacking pyhull (from axi==0.1)
  Downloading pyhull-2015.2.1.tar.gz (318kB): 318kB downloaded
  Running setup.py (path:/tmp/pip-build-uVKpez/pyhull/setup.py)
egg_info for package pyhull

    warning: no files found matching '*.md'
    warning: no files found matching '*.c'
    warning: no files found matching 'ez_setup.py'
    no previously-included directories found matching '**/tests'
Downloading/unpacking cairocffi (from axi==0.1)
  Downloading cairocffi-1.0.2.tar.gz (68kB): 68kB downloaded
  Running setup.py (path:/tmp/pip-build-uVKpez/cairocffi/setup.py)
egg_info for package cairocffi
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-uVKpez/cairocffi/setup.py", line 7, in <module>
        'cairocffi does not support Python 2.x anymore. '
    RuntimeError: cairocffi does not support Python 2.x anymore.
Please use Python 3 or install an older version of cairocffi.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-uVKpez/cairocffi/setup.py", line 7, in <module>

    'cairocffi does not support Python 2.x anymore. '

RuntimeError: cairocffi does not support Python 2.x anymore. Please
use Python 3 or install an older version of cairocffi.

**Comment by fogleman** [comment]
Looks like you're running a 2.x pip

**Comment by PaulHaeberli** [comment]
Thanks - i think it's working now.
